### ISSUE TITLE
[功能优化] 附件内图片展示效果优化

### ISSUE THREAD

**Issue by GalvinGao** [halo-dev/halo-admin#266]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

# 问题
由于图片很多时候并非附件展示区域所定义的宽高比，故在使用非常规宽高比图片时会产生不自然的拉伸效果

# 提案
- 对所有图片进行宽高比自适应
- 添加轻微程度的阴影以标识图片的实际边界

可参考以下 CSS 进行修改

```css
.attach-item img, .attach-item span, .attach-thumb img, .photo-thumb img {
    width: auto;
    display: inline-block;
    margin-left: 50%;
    transform: translateX(-50%);
    -ms-transform: translateX(-50%);

    filter: drop-shadow(0 0 4px rgba(0, 0, 0, .15));
    padding: 8px;
}
```

### 修改前
![image](https://user-images.githubusercontent.com/12567059/99515019-61255780-29c7-11eb-9690-66b1b80cb7c6.png)

### 修改后
![image](https://user-images.githubusercontent.com/12567059/99514995-58cd1c80-29c7-11eb-8253-d84f894bc5e5.png)

希望考虑一下 :D
